// TODO: automatically generate this file
#define OP_NOP          0x00
#define OP_LDZ          0x01
#define OP_STZ          0x02
#define OP_LDAI         0x03
#define OP_LDAM         0x04
#define OP_STA          0x05
#define OP_ADDI         0x06
#define OP_ADDM         0x07
#define OP_SUBI         0x08
#define OP_SUBM         0x09
#define OP_ADCI         0x0A
#define OP_ADCM         0x0B
#define OP_SBCI         0x0C
#define OP_SBCM         0x0D
#define OP_CMPI         0x0E
#define OP_CMPM         0x0F
#define OP_SHLI         0x10
#define OP_SHRI         0x11
#define OP_ANDI         0x12
#define OP_XORI         0x13
#define OP_SHL          0x14
#define OP_SHR          0x15
#define OP_ANDM         0x16
#define OP_XORM         0x17
#define OP_SHLM         0x18
#define OP_SHRM         0x19
#define OP_ORI          0x1A
#define OP_ORM          0x1E
#define OP_JMP          0x20
#define OP_JZ           0x21
#define OP_JC           0x22
#define OP_JNZ          0x23
#define OP_JNC          0x24
#define OP_STPC         0x25
#define OP_INC          0x26
#define OP_DEC          0x27
#define OP_INCM         0x28
#define OP_DECM         0x29